ai_services:
  google_cloud_vision:
    enabled: true
    credentials_file: "pdf-read-451916-86851702569b.json"
    region: "us-east1"

  amazon_textract:
    enabled: false
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: "us-east-1"
